title = "GitLeaks Config"
description = "GitLeaks configuration to detect secrets in the project"

[[rules]]
description = "Generic API Key"
regex = '''api\.secret\.key\s*=\s*['"]?[0-9A-Z\-]+['"]?'''
tags = ["apikey"]
